[workspace]
resolver = "2"
members = [
  "firmware/",
  "usb-client/",
]

# [profile.release]
# lto = true
# opt-level = "s"
# incremental = false
# codegen-units = 1
# # note: debug = true is okay - debuginfo isn't flashed to the device!
# debug = 2
